name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11, 17 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - run: mvn -B install --no-transfer-progress
      - name: Analyse code and publish to SonarQube 📊
        run: mvn -B -Dsonar.password=${{ secrets.SONAR_PASSWORD }} sonar:sonar
